# -*- coding: utf-8 -*-

"""
mdnotesccg

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import unittest

from mdnotesccg.configuration import Configuration
from mdnotesccg.configuration import Environment
from mdnotesccg.mdnotesccg_client import MdnotesccgClient
from mdnotesccg.http.auth.o_auth_2 import OAuth2


class ControllerTestBase(unittest.TestCase):

    """All test classes inherit from this base class. It abstracts out
    common functionality and configuration variables set up."""

    @classmethod
    def setUpClass(cls):
        """Class method called once before running tests in a test class."""
        cls.request_timeout = 30
        cls.assert_precision = 0.01
        cls.config = ControllerTestBase.create_configuration()
        cls.client = MdnotesccgClient()
        token = OAuth2.authorize(cls.config)
        cls.config = cls.config.clone_with(o_auth_token= token)

    @staticmethod
    def create_configuration():
        return Configuration(
            o_auth_client_id='23',
            o_auth_client_secret='tQNSqQlXBIwZcY9auoujQ57ckDcoh3t8UPbBRkSF'
        )
