# -*- coding: utf-8 -*-

"""
mdnotesccg

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from mdnotesccg.api_helper import APIHelper
from mdnotesccg.configuration import Server
from mdnotesccg.controllers.base_controller import BaseController
from mdnotesccg.models.o_auth_token import OAuthToken
from mdnotesccg.exceptions.o_auth_provider_exception import OAuthProviderException


class OAuthAuthorizationController(BaseController):

    """A Controller to access Endpoints in the mdnotesccg API."""

    def __init__(self, config, call_back=None):
        super(OAuthAuthorizationController, self).__init__(config, call_back)

    def request_token(self,
                      authorization,
                      scope=None,
                      _optional_form_parameters=None):
        """Does a POST request to /request_token.

        Create a new OAuth 2 token.

        Args:
            authorization (string): Authorization header in Basic auth format
            scope (string, optional): Requested scopes as a space-delimited
                list.
            _optional_form_parameters (Array, optional): Additional optional
                form parameters are supported by this endpoint

        Returns:
            OAuthToken: Response from the API.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        # Prepare query URL
        _url_path = '/request_token'
        _query_builder = self.config.get_base_uri(Server.AUTH)
        _query_builder += _url_path
        _query_url = APIHelper.clean_url(_query_builder)

        # Prepare headers
        _headers = {
            'accept': 'application/json',
            'Authorization': authorization
        }

        # Prepare form parameters
        _form_parameters = {
            'grant_type': 'client_credentials',
            'scope': scope
        }
        if _form_parameters is not None and _optional_form_parameters is not None:
            _form_parameters.update(
                APIHelper.form_encode_parameters(_optional_form_parameters)
            )
        _form_parameters = APIHelper.form_encode_parameters(_form_parameters)

        # Prepare and execute request
        _request = self.config.http_client.post(_query_url, headers=_headers, parameters=_form_parameters)
        _response = self.execute_request(_request)

        # Endpoint and global error handling using HTTP status codes.
        if _response.status_code == 400:
            raise OAuthProviderException('OAuth 2 provider returned an error.', _response)
        elif _response.status_code == 401:
            raise OAuthProviderException('OAuth 2 provider says client authentication failed.', _response)
        self.validate_response(_response)

        decoded = APIHelper.json_deserialize(_response.text, OAuthToken.from_dictionary)

        return decoded
